### ISSUE TITLE
build ChanGa on daint 

### ISSUE THREAD

**Issue by jgphpc** [trquinn/changa#7]
Hi,

Trying to build ChanGa on daint (cpu only as a starter) fails with: 

```
make: *** No rule to make target 'comlib.h', needed by 'DataManager.o'.  Stop.
```

I cloned master from https://github.com/trquinn/changa.git
then configure (using charm-6.7.1/gni-crayxc-smp) and make.

I also get issue with the Reductions.decl.h missing.
This is my very 1st attempt to build Changa, could you help me getting started or do you know someone i could ask for support ?

Thanks,

**Comment by insaneinside** [comment]
This is not the main repository for ChaNGa; I believe you want the Git repository at http://charm.cs.illinois.edu/gerrit/cosmo/changa

Tom, maybe you should close this fork?

**Comment by trquinn** [comment]
I just did an upstream merge for this fork, (although closing it might be better).

Also note that GPU support is being actively worked on.  If you use the UIUC repository (or the github mirror: https://github.com/N-BodyShop/changa ) be sure to do the following:
1) Use the 6.8.0 beta release of charm.
2) Look at patches on the gerrit web site mentioned above (search for cosmo/changa).

**Comment by jgphpc** [comment]
👍 I downloaded and built charm++/680b2 and Changa/gerrit and testdata (tested on cpu only) runs fine, thanks a lot.
